import type { Metadata } from "next";
import "./globals.css";
import { clashDisplay } from "@/common/lib/font";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

export const metadata: Metadata = {
  title: "Possible Evs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${clashDisplay.className} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
